project:
  type: book
  output-dir: docs

book:
  title: "analyticsedge"
  author: "Mridul Jain"
  date: "07/02/2023"
  chapters:
    - index.qmd
    - Units/Unit1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt